"HeroMastery"
{
    "npc_dota_hero_abaddon" {
        "support_mastery"   "1"
        "heal_mastery"      "1"
        "sword_mastery"     "1"
    }
    "npc_dota_hero_abyssal_underlord" {
        "trap_mastery"  "1"
        "fire_mastery"      "1"
        "dark_mastery"      "1"
    }
    "npc_dota_hero_alchemist" {
        "rage_mastery"  "1"
        "explosive_mastery" "1"
        "aghanim_synth" "1"
    }
    "npc_dota_hero_ancient_apparition" {
        "ice_mastery"   "1"
        "long_range_mastery"        "1"
        "skillshot_mastery"     "1"
    }
    "npc_dota_hero_antimage" {
        "blink_mastery" "1"
        "ultimate_mastery"      "1"
    }
    "npc_dota_hero_arc_warden" {
        "lightning_mastery" "1"
        "trap_mastery"      "1"
        "summon_mastery"        "1"
    }
    "npc_dota_hero_axe" {
        "brawl_mastery" "1"
        "kill_mastery"      "1"
    }
    "npc_dota_hero_bane" {
        "drain_mastery" "1"
        "channeling_mastery"        "1"
        "dark_mastery"      "1"
    }
    "npc_dota_hero_batrider" {
        "fire_mastery"  "1"
        "displacer"     "1"
        "fast_flyer"        "1"
    }
    "npc_dota_hero_beastmaster" {
        "beast_mastery" "1"
        "summon_mastery"        "1"
        "aura_mastery"      "1"
    }
    "npc_dota_hero_bloodseeker" {
        "blood_mastery" "1"
        "rage_mastery"      "1"
        "silence_mastery"       "1"
    }
    "npc_dota_hero_bounty_hunter" {
        "tracking_mastery"  "1"
        "invisible_mastery"     "1"
    }
    "npc_dota_hero_brewmaster" {
        "brawl_mastery" "1"
        "elemental_mastery"     "1"
        "drunken_mastery"       "1"
    }
    "npc_dota_hero_bristleback" {
        "brawl_mastery" "1"
        "rage_mastery"      "1"
        "spell_spammer"     "1"
    }
    "npc_dota_hero_broodmother" {
        "summon_mastery"    "1"
        "poison_mastery"        "1"
        "invisible_mastery"     "1"
    }
    "npc_dota_hero_centaur" {
        "brawl_mastery" "1"
        "beast_mastery"     "1"
        "blood_mastery"     "1"
    }
    "npc_dota_hero_chaos_knight" {
        "illusion_mastery"  "1"
        "dark_mastery"      "1"
        "chaos_mastery"     "1"
    }
    "npc_dota_hero_chen" {
        "heal_mastery"  "1"
        "light_mastery"     "1"
        "natural_jungler"       "1"
    }
    "npc_dota_hero_clinkz" {
        "fire_mastery"  "1"
        "invisible_mastery"     "1"
        "demolisher"        "1"
    }
    "npc_dota_hero_crystal_maiden" {
        "ice_mastery"   "1"
        "support_mastery"       "1"
        "aura_mastery"      "1"
    }
    "npc_dota_hero_dark_seer" {
        "dark_mastery"  "1"
        "illusion_mastery"      "1"
        "displacer"     "1"
    }
    "npc_dota_hero_dazzle" {
        "support_mastery"   "1"
        "heal_mastery"      "1"
        "poison_mastery"        "1"
    }
    "npc_dota_hero_death_prophet" {
        "drain_mastery" "1"
        "ultimate_mastery"      "1"
        "silence_mastery"       "1"
    }
    "npc_dota_hero_disruptor" {
        "support_mastery"   "1"
        "displacer"     "1"
        "lightning_mastery"     "1"
    }
    "npc_dota_hero_doom_bringer" {
        "fire_mastery"  "1"
        "ultimate_mastery"      "1"
        "natural_jungler"       "1"
    }
    "npc_dota_hero_dragon_knight" {
        "fire_mastery"  "1"
        "blood_mastery"     "1"
        "demolisher"        "1"
    }
    "npc_dota_hero_drow_ranger" {
        "silence_mastery"   "1"
        "ice_mastery"       "1"
        "long_range_mastery"        "1"
    }
    "npc_dota_hero_earth_spirit" {
        "earth_mastery" "1"
        "skillshot_mastery"     "1"
        "support_mastery"       "1"
    }
    "npc_dota_hero_earthshaker" {
        "earth_mastery" "1"
        "long_range_mastery"        "1"
        "brawl_mastery"     "1"
    }
    "npc_dota_hero_elder_titan" {
        "earth_mastery" "1"
        "long_range_mastery"        "1"
        "aura_mastery"      "1"
    }
    "npc_dota_hero_ember_spirit" {
        "fire_mastery"  "1"
        "sword_mastery"     "1"
        "skillshot_mastery"     "1"
    }
    "npc_dota_hero_enchantress" {
        "nature_mastery"    "1"
        "long_range_mastery"        "1"
        "natural_jungler"       "1"
    }
    "npc_dota_hero_enigma" {
        "ultimate_mastery"  "1"
        "summon_mastery"        "1"
        "natural_jungler"       "1"
    }
    "npc_dota_hero_faceless_void" {
        "ultimate_mastery"  "1"
        "chrono_mastery"        "1"
        "bash_lord"     "1"
    }
    "npc_dota_hero_furion" {
        "nature_mastery"    "1"
        "summon_mastery"        "1"
        "long_range_mastery"        "1"
    }
    "npc_dota_hero_gyrocopter" {
        "explosive_mastery" "1"
        "spell_spammer"     "1"
        "side_gunner"       "1"
    }
    "npc_dota_hero_huskar" {
        "blood_mastery" "1"
        "heal_mastery"      "1"
        "fire_mastery"      "1"
    }
    "npc_dota_hero_invoker" {
        "elemental_mastery" "1"
        "spell_mastery"     "1"
    }
    "npc_dota_hero_jakiro" {
        "fire_mastery"  "1"
        "ice_mastery"       "1"
        "fast_flyer"        "1"
    }
    "npc_dota_hero_juggernaut" {
        "sword_mastery" "1"
        "heal_mastery"      "1"
    }
    "npc_dota_hero_keeper_of_the_light" {
        "support_mastery"   "1"
        "light_mastery"     "1"
        "day_vision"        "1"
    }
    "npc_dota_hero_kunkka" {
        "water_mastery" "1"
        "sword_mastery"     "1"
        "drunken_mastery"       "1"
    }
    "npc_dota_hero_legion_commander" {
        "brawl_mastery" "1"
        "sword_mastery"     "1"
        "support_mastery"       "1"
    }
    "npc_dota_hero_leshrac" {
        "earth_mastery" "1"
        "lightning_mastery"     "1"
        "demolisher"        "1"
    }
    "npc_dota_hero_lich" {
        "ice_mastery"   "1"
        "support_mastery"       "1"
        "drain_mastery"     "1"
    }
    "npc_dota_hero_life_stealer" {
        "rage_mastery"  "1"
        "blood_mastery"     "1"
        "natural_jungler"       "1"
    }
    "npc_dota_hero_lina" {
        "fire_mastery"  "1"
        "long_range_mastery"        "1"
    }
    "npc_dota_hero_lion" {
        "hex_mastery"   "1"
        "drain_mastery"     "1"
        "kill_mastery"      "1"
    }
    "npc_dota_hero_lone_druid" {
        "nature_mastery"    "1"
        "beast_mastery"     "1"
        "natural_jungler"       "1"
    }
    "npc_dota_hero_luna" {
        "ultimate_mastery"  "1"
        "aura_mastery"      "1"
        "demolisher"        "1"
    }
    "npc_dota_hero_lycan" {
        "beast_mastery" "1"
        "summon_mastery"        "1"
        "natural_jungler"       "1"
    }
    "npc_dota_hero_magnataur" {
        "displacer" "1"
        "ultimate_mastery"      "1"
        "beast_mastery"     "1"
    }
    "npc_dota_hero_medusa" {
        "drain_mastery" "1"
        "ultimate_mastery"      "1"
        "toggle_mastery"        "1"
    }
    "npc_dota_hero_meepo" {
        "earth_mastery" "1"
        "trap_mastery"      "1"
        "meepo_mastery"     "1"
    }
    "npc_dota_hero_mirana" {
        "skillshot_mastery" "1"
        "invisible_mastery"     "1"
    }
    "npc_dota_hero_monkey_king" {
        "beast_mastery" "1"
        "brawl_mastery"     "1"
        "long_range_mastery"        "1"
    }
    "npc_dota_hero_morphling" {
        "water_mastery" "1"
        "illusion_mastery"      "1"
        "toggle_mastery"        "1"
    }
    "npc_dota_hero_naga_siren" {
        "water_mastery" "1"
        "illusion_mastery"      "1"
        "ultimate_mastery"      "1"
    }
    "npc_dota_hero_necrolyte" {
        "heal_mastery"  "1"
        "kill_mastery"      "1"
        "aura_mastery"      "1"
    }
    "npc_dota_hero_nevermore" {
        "dark_mastery"  "1"
        "soul_mastery"      "1"
        "demolisher"        "1"
    }
    "npc_dota_hero_night_stalker" {
        "dark_mastery"  "1"
        "silence_mastery"       "1"
        "night_vision"      "1"
    }
    "npc_dota_hero_nyx_assassin" {
        "earth_mastery" "1"
        "kill_mastery"      "1"
        "invisible_mastery"     "1"
    }
    "npc_dota_hero_obsidian_destroyer" {
        "ultimate_mastery"  "1"
        "spell_mastery"     "1"
        "aura_mastery"      "1"
    }
    "npc_dota_hero_ogre_magi" {
        "fire_mastery"  "1"
        "blood_mastery"     "1"
        "dumb_luck"     "1"
    }
    "npc_dota_hero_omniknight" {
        "light_mastery" "1"
        "heal_mastery"      "1"
        "aura_mastery"      "1"
    }
    "npc_dota_hero_oracle" {
        "support_mastery"   "1"
        "heal_mastery"      "1"
        "spell_spammer"     "1"
    }
    "npc_dota_hero_phantom_assassin" {
        "dagger_mastery"    "1"
        "blink_mastery"     "1"
        "spell_spammer"     "1"
    }
    "npc_dota_hero_phantom_lancer" {
        "illusion_mastery"  "1"
        "brawl_mastery"     "1"
    }
    "npc_dota_hero_phoenix" {
        "fire_mastery"  "1"
        "heal_mastery"      "1"
        "fast_flyer"        "1"
    }
    "npc_dota_hero_puck" {
        "silence_mastery"   "1"
        "blink_mastery"     "1"
        "fast_flyer"        "1"
    }
    "npc_dota_hero_pudge" {
        "skillshot_mastery" "1"
        "flesh_heap_mastery"        "1"
    }
    "npc_dota_hero_pugna" {
        "drain_mastery" "1"
        "channeling_mastery"        "1"
        "demolisher"        "1"
    }
    "npc_dota_hero_queenofpain" {
        "blink_mastery" "1"
        "dagger_mastery"        "1"
        "dominatrix"        "1"
    }
    "npc_dota_hero_rattletrap" {
        "mechanial_mastery" "1"
        "skillshot_mastery"     "1"
        "side_rockets"      "1"
    }
    "npc_dota_hero_razor" {
        "lightning_mastery" "1"
        "drain_mastery"     "1"
    }
    "npc_dota_hero_riki" {
        "dagger_mastery"    "1"
        "blink_mastery"     "1"
        "invisible_mastery"     "1"
    }
    "npc_dota_hero_rubick" {
        "spell_mastery"     "1"
        "support_mastery"   "1"
        "aura_mastery"      "1"
    }
    "npc_dota_hero_sand_king" {
        "earth_mastery" "1"
        "support_mastery"       "1"
        "channeling_mastery"        "1"
    }
    "npc_dota_hero_shadow_demon" {
        "support_mastery"   "1"
        "poison_mastery"        "1"
        "illusion_mastery"      "1"
    }
    "npc_dota_hero_shadow_shaman" {
        "channeling_mastery"    "1"
        "hex_mastery"       "1"
        "summon_mastery"        "1"
    }
    "npc_dota_hero_shredder" {
        "mechanical_mastery"    "1"
        "spell_spammer"     "1"
        "tree_destroyer"        "1"
    }
    "npc_dota_hero_silencer" {
        "silence_mastery"   "1"
        "intelligence_steal"        "1"
    }
    "npc_dota_hero_skeleton_king" {
        "rage_mastery"  "1"
        "sword_mastery"     "1"
        "aura_mastery"      "1"
    }
    "npc_dota_hero_skywrath_mage" {
        "long_range_mastery"    "1"
        "spell_spammer"     "1"
        "silence_mastery"       "1"
    }
    "npc_dota_hero_slardar" {
        "water_mastery" "1"
        "brawl_mastery"     "1"
        "bash_lord"     "1"
    }
    "npc_dota_hero_slark" {
        "water_mastery" "1"
        "dark_mastery"      "1"
        "invisible_mastery"     "1"
    }
    "npc_dota_hero_sniper" {
        "long_range_mastery"        "1"
        "explosive_mastery" "1"
    }
    "npc_dota_hero_spectre" {
        "dagger_mastery"    "1"
        "ultimate_mastery"      "1"
        "illusion_mastery"      "1"
    }
    "npc_dota_hero_spirit_breaker" {
        "dark_mastery"  "1"
        "brawl_mastery"     "1"
        "bash_lord"     "1"
    }
    "npc_dota_hero_storm_spirit" {
        "lightning_mastery" "1"
        "displacer"     "1"
        "spell_spammer"     "1"
    }
    "npc_dota_hero_sven" {
        "sword_mastery" "1"
        "natural_cleave"        "1"
    }
    "npc_dota_hero_techies" {
        "explosive_mastery" "1"
        "trap_mastery"      "1"
        "long_range_mastery"        "1"
    }
    "npc_dota_hero_templar_assassin" {
        "trap_mastery"  "1"
        "invisible_mastery"     "1"
    }
    "npc_dota_hero_terrorblade" {
        "dark_mastery"  "1"
        "illusion_mastery"      "1"
        "aura_mastery"      "1"
    }
    "npc_dota_hero_tidehunter" {
        "ultimate_mastery"  "1"
        "water_mastery"     "1"
        "spell_spammer"     "1"
    }
    "npc_dota_hero_tinker" {
        "mechanical_mastery"    "1"
        "long_range_mastery"        "1"
        "spell_spammer"     "1"
    }
    "npc_dota_hero_tiny" {
        "earth_mastery" "1"
        "natural_cleave"        "1"
        "demolisher"        "1"
    }
    "npc_dota_hero_treant" {
        "nature_mastery"    "1"
        "heal_mastery"      "1"
        "invisible_mastery"     "1"
    }
    "npc_dota_hero_troll_warlord" {
        "rage_mastery"  "1"
        "bash_lord"     "1"
    }
    "npc_dota_hero_tusk" {
        "brawl_mastery" "1"
        "ice_mastery"       "1"
        "support_mastery"       "1"
    }
    "npc_dota_hero_undying" {
        "support_mastery"   "1"
        "heal_mastery"      "1"
        "drain_mastery"     "1"
    }
    "npc_dota_hero_ursa" {
        "beast_mastery" "1"
        "rage_mastery"      "1"
        "natural_jungler"       "1"
    }
    "npc_dota_hero_vengefulspirit" {
        "support_mastery"   "1"
        "displacer"     "1"
        "vengeance"     "1"
    }
    "npc_dota_hero_venomancer" {
        "poison_mastery"    "1"
        "summon_mastery"        "1"
        "natural_jungler"       "1"
    }
    "npc_dota_hero_viper" {
        "poison_mastery"    "1"
        "fast_flyer"        "1"
    }
    "npc_dota_hero_visage" {
        "summon_mastery"    "1"
        "spell_spammer"     "1"
        "fast_flyer"        "1"
    }
    "npc_dota_hero_warlock" {
        "support_mastery"   "1"
        "summon_mastery"        "1"
        "channeling_mastery"        "1"
    }
    "npc_dota_hero_weaver" {
        "invisible_mastery" "1"
        "auto_time_lapse"       "1"
    }
    "npc_dota_hero_windrunner" {
        "long_range_mastery"    "1"
        "skillshot_mastery"     "1"
        "nature_mastery"        "1"
    }
    "npc_dota_hero_winter_wyvern" {
        "ice_mastery"   "1"
        "heal_mastery"      "1"
        "fast_flyer"        "1"
    }
    "npc_dota_hero_wisp" {
        "support_mastery"   "1"
        "light_mastery"     "1"
        "heal_mastery"      "1"
    }
    "npc_dota_hero_witch_doctor" {
        "support_mastery"   "1"
        "heal_mastery"      "1"
        "channeling_mastery"        "1"
    }
    "npc_dota_hero_zuus" {
        "lightning_mastery" "1"
        "long_range_mastery"        "1"
        "spell_spammer"     "1"
    }
}